### ISSUE TITLE
Crash on launch (1.19.4 Quilt)

### ISSUE THREAD

**Issue by solamint** [Scotsguy/now-playing#26]
Upon loading into Minecraft, _NowPlayingToast.class_ throws an error.

```
[17:14:16] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IncompatibleClassChangeError: Expecting non-static method 'void net.minecraft.class_332.method_25302(net.minecraft.class_4587, int, int, int, int, int, int)'
	at com.github.scotsguy.nowplaying.NowPlayingToast.renderBackgroundRow(NowPlayingToast.java:83) ~[transformed-mod-now-playing.i0:0/:?]
	at com.github.scotsguy.nowplaying.NowPlayingToast.method_1986(NowPlayingToast.java:54) ~[transformed-mod-now-playing.i0:0/:?]
	at net.minecraft.class_374$class_375.method_2002(class_374.java:154) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_374.method_45074(class_374.java:37) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
	at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
	at net.minecraft.class_374.method_1996(class_374.java:36) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:964) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

Happens when music starts playing on the main menu.

Log: [https://mclo.gs/RDPmxCw](https://mclo.gs/RDPmxCw)

**Comment by mafatik** [comment]
I have the same thing only on fabric 1.19.4 xd

**Comment by mysticoreo** [comment]
Same on Forge 1.19.4

**Comment by NotRyken** [comment]
Closing this as versions prior to mc1.21 are no longer supported. 
Please open a new issue if the problem persists on latest release.
